Ext.define('MobileJudge.store.stats.QuestionGrades', {
    extend: 'Ext.data.Store',
    alias: 'store.questionGrades',
    storeId: 'questionGrades',
    fields: ['questionId', 'grade'],
    data: {
        items: [{
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 9.2500
        }, {
            "questionId": 18,
            "grade": 9.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 9.2500
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 10.0000
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 5.0000
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 9.6667
        }, {
            "questionId": 17,
            "grade": 10.0000
        }, {
            "questionId": 18,
            "grade": 9.6667
        }, {
            "questionId": 19,
            "grade": 9.6667
        }, {
            "questionId": 20,
            "grade": 9.6667
        }, {
            "questionId": 19,
            "grade": 7.0000
        }, {
            "questionId": 20,
            "grade": 5.0000
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 9.0000
        }, {
            "questionId": 18,
            "grade": 6.0000
        }, {
            "questionId": 19,
            "grade": 9.6667
        }, {
            "questionId": 20,
            "grade": 8.6667
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 10.0000
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 7.3333
        }, {
            "questionId": 17,
            "grade": 6.6667
        }, {
            "questionId": 18,
            "grade": 7.3333
        }, {
            "questionId": 19,
            "grade": 7.3333
        }, {
            "questionId": 20,
            "grade": 2.6667
        }, {
            "questionId": 16,
            "grade": 8.5000
        }, {
            "questionId": 17,
            "grade": 4.5000
        }, {
            "questionId": 18,
            "grade": 7.0000
        }, {
            "questionId": 19,
            "grade": 5.0000
        }, {
            "questionId": 20,
            "grade": 7.0000
        }, {
            "questionId": 16,
            "grade": 9.0000
        }, {
            "questionId": 17,
            "grade": 9.0000
        }, {
            "questionId": 18,
            "grade": 9.0000
        }, {
            "questionId": 19,
            "grade": 9.6667
        }, {
            "questionId": 20,
            "grade": 8.0000
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 10.0000
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 10.0000
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 9.0000
        }, {
            "questionId": 17,
            "grade": 9.0000
        }, {
            "questionId": 18,
            "grade": 9.5000
        }, {
            "questionId": 19,
            "grade": 9.5000
        }, {
            "questionId": 20,
            "grade": 9.5000
        }, {
            "questionId": 16,
            "grade": 9.5000
        }, {
            "questionId": 17,
            "grade": 9.0000
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 9.5000
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 0.0000
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 9.0000
        }, {
            "questionId": 16,
            "grade": 9.4000
        }, {
            "questionId": 17,
            "grade": 9.2000
        }, {
            "questionId": 18,
            "grade": 9.0000
        }, {
            "questionId": 19,
            "grade": 9.4000
        }, {
            "questionId": 20,
            "grade": 7.2000
        }, {
            "questionId": 16,
            "grade": 7.6667
        }, {
            "questionId": 17,
            "grade": 7.3333
        }, {
            "questionId": 18,
            "grade": 5.6667
        }, {
            "questionId": 19,
            "grade": 9.0000
        }, {
            "questionId": 20,
            "grade": 9.0000
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 10.0000
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 9.6667
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 8.0000
        }, {
            "questionId": 17,
            "grade": 8.5000
        }, {
            "questionId": 18,
            "grade": 9.5000
        }, {
            "questionId": 19,
            "grade": 9.5000
        }, {
            "questionId": 20,
            "grade": 9.5000
        }, {
            "questionId": 16,
            "grade": 9.0000
        }, {
            "questionId": 17,
            "grade": 9.0000
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 8.0000
        }, {
            "questionId": 16,
            "grade": 9.0000
        }, {
            "questionId": 17,
            "grade": 8.5000
        }, {
            "questionId": 18,
            "grade": 9.0000
        }, {
            "questionId": 19,
            "grade": 9.5000
        }, {
            "questionId": 20,
            "grade": 9.0000
        }, {
            "questionId": 16,
            "grade": 9.5000
        }, {
            "questionId": 17,
            "grade": 9.5000
        }, {
            "questionId": 18,
            "grade": 9.5000
        }, {
            "questionId": 19,
            "grade": 9.5000
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 5.7500
        }, {
            "questionId": 17,
            "grade": 5.5000
        }, {
            "questionId": 18,
            "grade": 6.7500
        }, {
            "questionId": 19,
            "grade": 7.7500
        }, {
            "questionId": 20,
            "grade": 7.2500
        }, {
            "questionId": 16,
            "grade": 8.7500
        }, {
            "questionId": 17,
            "grade": 8.7500
        }, {
            "questionId": 18,
            "grade": 8.5000
        }, {
            "questionId": 19,
            "grade": 8.7500
        }, {
            "questionId": 20,
            "grade": 8.0000
        }, {
            "questionId": 16,
            "grade": 9.0000
        }, {
            "questionId": 17,
            "grade": 8.6667
        }, {
            "questionId": 18,
            "grade": 7.3333
        }, {
            "questionId": 19,
            "grade": 9.3333
        }, {
            "questionId": 20,
            "grade": 9.3333
        }, {
            "questionId": 16,
            "grade": 9.6667
        }, {
            "questionId": 17,
            "grade": 9.6667
        }, {
            "questionId": 18,
            "grade": 9.0000
        }, {
            "questionId": 19,
            "grade": 9.6667
        }, {
            "questionId": 20,
            "grade": 9.3333
        }, {
            "questionId": 16,
            "grade": 9.3333
        }, {
            "questionId": 17,
            "grade": 8.6667
        }, {
            "questionId": 18,
            "grade": 8.6667
        }, {
            "questionId": 19,
            "grade": 8.6667
        }, {
            "questionId": 20,
            "grade": 6.6667
        }, {
            "questionId": 16,
            "grade": 8.7500
        }, {
            "questionId": 17,
            "grade": 8.7500
        }, {
            "questionId": 18,
            "grade": 7.0000
        }, {
            "questionId": 19,
            "grade": 8.2500
        }, {
            "questionId": 20,
            "grade": 8.2500
        }, {
            "questionId": 16,
            "grade": 8.7500
        }, {
            "questionId": 17,
            "grade": 7.5000
        }, {
            "questionId": 18,
            "grade": 7.0000
        }, {
            "questionId": 19,
            "grade": 9.2500
        }, {
            "questionId": 20,
            "grade": 5.7500
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 10.0000
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 9.0000
        }, {
            "questionId": 17,
            "grade": 8.6667
        }, {
            "questionId": 18,
            "grade": 9.6667
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 9.6667
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 9.0000
        }, {
            "questionId": 18,
            "grade": 9.0000
        }, {
            "questionId": 19,
            "grade": 9.0000
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 9.6667
        }, {
            "questionId": 17,
            "grade": 9.3333
        }, {
            "questionId": 18,
            "grade": 9.6667
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 5.3333
        }, {
            "questionId": 17,
            "grade": 5.3333
        }, {
            "questionId": 18,
            "grade": 6.3333
        }, {
            "questionId": 19,
            "grade": 5.6667
        }, {
            "questionId": 20,
            "grade": 3.0000
        }, {
            "questionId": 16,
            "grade": 7.5000
        }, {
            "questionId": 17,
            "grade": 8.5000
        }, {
            "questionId": 18,
            "grade": 8.5000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 7.5000
        }, {
            "questionId": 16,
            "grade": 8.3333
        }, {
            "questionId": 17,
            "grade": 7.6667
        }, {
            "questionId": 18,
            "grade": 8.0000
        }, {
            "questionId": 19,
            "grade": 7.3333
        }, {
            "questionId": 20,
            "grade": 6.6667
        }, {
            "questionId": 16,
            "grade": 9.5000
        }, {
            "questionId": 17,
            "grade": 9.5000
        }, {
            "questionId": 18,
            "grade": 9.5000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 10.0000
        }, {
            "questionId": 18,
            "grade": 7.5000
        }, {
            "questionId": 19,
            "grade": 9.5000
        }, {
            "questionId": 20,
            "grade": 8.5000
        }, {
            "questionId": 16,
            "grade": 8.0000
        }, {
            "questionId": 17,
            "grade": 8.6667
        }, {
            "questionId": 18,
            "grade": 7.3333
        }, {
            "questionId": 19,
            "grade": 9.3333
        }, {
            "questionId": 20,
            "grade": 9.3333
        }, {
            "questionId": 16,
            "grade": 9.3333
        }, {
            "questionId": 17,
            "grade": 8.3333
        }, {
            "questionId": 18,
            "grade": 8.6667
        }, {
            "questionId": 19,
            "grade": 9.3333
        }, {
            "questionId": 20,
            "grade": 8.6667
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 9.5000
        }, {
            "questionId": 18,
            "grade": 9.5000
        }, {
            "questionId": 19,
            "grade": 9.5000
        }, {
            "questionId": 20,
            "grade": 8.0000
        }, {
            "questionId": 16,
            "grade": 9.3333
        }, {
            "questionId": 17,
            "grade": 8.6667
        }, {
            "questionId": 18,
            "grade": 9.6667
        }, {
            "questionId": 19,
            "grade": 9.0000
        }, {
            "questionId": 20,
            "grade": 8.3333
        }, {
            "questionId": 16,
            "grade": 8.7500
        }, {
            "questionId": 17,
            "grade": 8.7500
        }, {
            "questionId": 18,
            "grade": 8.5000
        }, {
            "questionId": 19,
            "grade": 9.0000
        }, {
            "questionId": 20,
            "grade": 6.7500
        }, {
            "questionId": 16,
            "grade": 7.5000
        }, {
            "questionId": 17,
            "grade": 8.0000
        }, {
            "questionId": 18,
            "grade": 8.0000
        }, {
            "questionId": 19,
            "grade": 9.0000
        }, {
            "questionId": 20,
            "grade": 9.0000
        }, {
            "questionId": 16,
            "grade": 8.5000
        }, {
            "questionId": 17,
            "grade": 9.0000
        }, {
            "questionId": 18,
            "grade": 8.5000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 9.0000
        }, {
            "questionId": 17,
            "grade": 10.0000
        }, {
            "questionId": 18,
            "grade": 9.5000
        }, {
            "questionId": 19,
            "grade": 9.5000
        }, {
            "questionId": 20,
            "grade": 4.0000
        }, {
            "questionId": 16,
            "grade": 9.6667
        }, {
            "questionId": 17,
            "grade": 8.3333
        }, {
            "questionId": 18,
            "grade": 9.3333
        }, {
            "questionId": 19,
            "grade": 9.6667
        }, {
            "questionId": 20,
            "grade": 9.3333
        }, {
            "questionId": 16,
            "grade": 9.0000
        }, {
            "questionId": 17,
            "grade": 8.5000
        }, {
            "questionId": 18,
            "grade": 8.5000
        }, {
            "questionId": 19,
            "grade": 9.0000
        }, {
            "questionId": 20,
            "grade": 9.5000
        }, {
            "questionId": 16,
            "grade": 9.6667
        }, {
            "questionId": 17,
            "grade": 9.6667
        }, {
            "questionId": 18,
            "grade": 9.6667
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 9.3333
        }, {
            "questionId": 16,
            "grade": 9.0000
        }, {
            "questionId": 17,
            "grade": 9.0000
        }, {
            "questionId": 18,
            "grade": 9.0000
        }, {
            "questionId": 19,
            "grade": 9.5000
        }, {
            "questionId": 20,
            "grade": 9.0000
        }, {
            "questionId": 16,
            "grade": 8.5000
        }, {
            "questionId": 17,
            "grade": 8.5000
        }, {
            "questionId": 18,
            "grade": 7.0000
        }, {
            "questionId": 19,
            "grade": 9.0000
        }, {
            "questionId": 20,
            "grade": 7.5000
        }, {
            "questionId": 16,
            "grade": 9.6667
        }, {
            "questionId": 17,
            "grade": 6.3333
        }, {
            "questionId": 18,
            "grade": 9.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 9.6667
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 10.0000
        }, {
            "questionId": 18,
            "grade": 9.0000
        }, {
            "questionId": 19,
            "grade": 9.0000
        }, {
            "questionId": 20,
            "grade": 4.0000
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 8.0000
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 9.0000
        }, {
            "questionId": 20,
            "grade": 8.0000
        }, {
            "questionId": 16,
            "grade": 7.5000
        }, {
            "questionId": 17,
            "grade": 9.7500
        }, {
            "questionId": 18,
            "grade": 9.2500
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 7.2500
        }, {
            "questionId": 16,
            "grade": 8.2500
        }, {
            "questionId": 17,
            "grade": 8.5000
        }, {
            "questionId": 18,
            "grade": 8.2500
        }, {
            "questionId": 19,
            "grade": 9.0000
        }, {
            "questionId": 20,
            "grade": 9.7500
        }, {
            "questionId": 16,
            "grade": 9.6667
        }, {
            "questionId": 17,
            "grade": 9.6667
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 6.6667
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 10.0000
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 8.0000
        }, {
            "questionId": 17,
            "grade": 8.5000
        }, {
            "questionId": 18,
            "grade": 9.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 8.5000
        }, {
            "questionId": 16,
            "grade": 8.6667
        }, {
            "questionId": 17,
            "grade": 8.6667
        }, {
            "questionId": 18,
            "grade": 8.0000
        }, {
            "questionId": 19,
            "grade": 9.0000
        }, {
            "questionId": 20,
            "grade": 7.0000
        }, {
            "questionId": 16,
            "grade": 10.0000
        }, {
            "questionId": 17,
            "grade": 10.0000
        }, {
            "questionId": 18,
            "grade": 10.0000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 10.0000
        }, {
            "questionId": 16,
            "grade": 8.5000
        }, {
            "questionId": 17,
            "grade": 8.7500
        }, {
            "questionId": 18,
            "grade": 9.2500
        }, {
            "questionId": 19,
            "grade": 9.2500
        }, {
            "questionId": 20,
            "grade": 4.2500
        }, {
            "questionId": 16,
            "grade": 9.3333
        }, {
            "questionId": 17,
            "grade": 9.0000
        }, {
            "questionId": 18,
            "grade": 8.6667
        }, {
            "questionId": 19,
            "grade": 5.6667
        }, {
            "questionId": 20,
            "grade": 9.3333
        }, {
            "questionId": 16,
            "grade": 9.7500
        }, {
            "questionId": 17,
            "grade": 9.5000
        }, {
            "questionId": 18,
            "grade": 9.5000
        }, {
            "questionId": 19,
            "grade": 10.0000
        }, {
            "questionId": 20,
            "grade": 9.7500
        }]
    },
    proxy: {
        type: 'memory',
        reader: {
            type: 'json',
            rootProperty: 'items'
        }
    }
});


Ext.define('MobileJudge.model.stats.QuestionAverage', {
    extend: 'Ext.data.Model',
    fields: ['questionId', 'average']
});


Ext.define('MobileJudge.store.stats.QuestionAverage', {
    extend: 'Ext.data.Store',
    alias: 'store.questionAverage',
    model: 'MobileJudge.model.stats.QuestionAverage',
    data: (function () {
        var data = [];
        var expense = Ext.createByAlias('store.questionGrades');
        console.log(expense);
        expense.group('questionId');
        var groups = expense.getGroups();
        console.log(groups);
        groups.each(function (group) {
            console.log(group);
            data.push({ questionId: group.config.groupKey, average: group.average('grade') });
        });
        return data;
    })()
});

